#include <Windows.h>
#include <stdio.h>
#include <iomanip>
#include <d3d9.h>
#include <d3dx9.h>
#include <iostream>


using namespace std;

//enum Type {
//	MARIO = 0,
//	BRICK = 1,
//	GOOMBA = 2,
//	KOOPAS = 3,
//	PLATFORM = 21,
//
//};


//-----------------------Key Control--------------------------





//-----------------------main
#define WINDOW_CLASS_NAME L"Super Mario Bros 3"
#define MAIN_WINDOW_TITLE L"Super Mario Bros 3"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(255, 255, 200)
#define SCREEN_WIDTH 300  
#define SCREEN_HEIGHT 300

#define MAX_FRAME_RATE 120

//-------------------------------map
#define TILE_WIDTH 16
#define TILE_HEIGHT 16

//----------------------------Game
#define DIRECTINPUT_VERSION 0x0800
#define KEYBOARD_BUFFER_SIZE 1024


#define MAX_GAME_LINE 1024


#define GAME_FILE_SECTION_UNKNOWN -1
#define GAME_FILE_SECTION_SETTINGS 1
#define GAME_FILE_SECTION_SCENES 2
//GameObject
#define ID_TEX_BBOX -100	

//------------------------------PlayScene
#define SCENE_SECTION_UNKNOWN -1
#define SCENE_SECTION_TEXTURES 2
#define SCENE_SECTION_SPRITES 3
#define SCENE_SECTION_ANIMATIONS 4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS	6
#define SCENE_SECTION_DRAWMAP 7
#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_PLATFORM 1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COLORBLOCK 4
#define OBJECT_TYPE_BRICK	5
#define OBJECT_TYPE_PORTAL	50


#define MAX_SCENE_LINE 1024
#define SCENE_TEST 1
//-----------------------------Goomba
#define GOOMBA_WALKING_SPEED 0.05f;

#define GOOMBA_BBOX_WIDTH 16
#define GOOMBA_BBOX_HEIGHT 15
#define GOOMBA_BBOX_HEIGHT_DIE 9

#define GOOMBA_STATE_WALKING 100
#define GOOMBA_STATE_DIE 200

#define GOOMBA_ANI_WALKING 0
#define GOOMBA_ANI_DIE 1

//-----------------------------Koopas
#define KOOPAS_WALKING_SPEED 0.03f;

#define KOOPAS_BBOX_WIDTH 16
#define KOOPAS_BBOX_HEIGHT 26
#define KOOPAS_BBOX_HEIGHT_DIE 16

#define KOOPAS_STATE_WALKING 100
#define KOOPAS_STATE_DIE 200

#define KOOPAS_ANI_WALKING_LEFT 0
#define KOOPAS_ANI_WALKING_RIGHT 1
#define KOOPAS_ANI_DIE 2

//--------------------Brick
#define BRICK_BBOX_WIDTH  16
#define BRICK_BBOX_HEIGHT 16

//----------------------Mario 
#define MARIO_WALKING_SPEED					0.01f 
#define MARIO_RUNNING_SPEED					0.015f
#define MARIO_RUNNING_MAXSPEED				0.03f
#define MARIO_JUMP_SPEED					0.01f
#define MARIO_FLY_SPEED						0.02f
#define MARIO_JUMP_SPEED_PEEK				0.005f
#define MARIO_JUMP_DEFLECT_SPEED			0.2f
#define MARIO_GRAVITY						0.002f
#define MARIO_DIE_DEFLECT_SPEED				0.5f
#define MARIO_DECELERATE_SPEED				0.05f

#define MARIO_STATE_IDLE				0
#define MARIO_STATE_WALK_RIGHT			100
#define MARIO_STATE_WALK_LEFT			200
#define MARIO_STATE_RUN_RIGHT			300
#define MARIO_STATE_RUN_LEFT			400
#define MARIO_STATE_JUMP				500
#define MARIO_STATE_FLY_RIGHT			600
#define MARIO_STATE_FLY_LEFT			700
#define MARIO_STATE_DIE					800
#define MARIO_STATE_SIT					900
#define MARIO_STATE_TURN				1000

#define MARIO_ANI_BIG_IDLE_RIGHT			0
#define MARIO_ANI_BIG_IDLE_LEFT				1
#define MARIO_ANI_SMALL_IDLE_RIGHT			2
#define MARIO_ANI_SMALL_IDLE_LEFT			3
#define MARIO_ANI_BIG_WALK_RIGHT			4
#define MARIO_ANI_BIG_WALK_LEFT				5
#define MARIO_ANI_SMALL_WALK_RIGHT			6
#define MARIO_ANI_SMALL_WALK_LEFT			7
#define MARIO_ANI_BIG_RUN_RIGHT				8
#define MARIO_ANI_BIG_RUN_LEFT				9
#define MARIO_ANI_BIG_JUMP_RIGHT			10
#define MARIO_ANI_BIG_JUMP_LEFT				11
#define MARIO_ANI_SMALL_JUMP_LEFT			12
#define MARIO_ANI_SMALL_JUMP_RIGHT			13
#define MARIO_ANI_SMALL_RUN_RIGHT			14
#define MARIO_ANI_SMALL_RUN_LEFT			15
#define MARIO_ANI_BIG_SIT_RIGHT				16
#define MARIO_ANI_BIG_SIT_LEFT				17
#define MARIO_ANI_BIG_TURN_LEFT				18
#define MARIO_ANI_BIG_TURN_RIGHT			19
#define MARIO_ANI_SMALL_TURN_LEFT			20
#define MARIO_ANI_SMALL_TURN_RIGHT			21
#define MARIO_ANI_BIG_RUN_RIGHT_MAXSPEED	22
#define MARIO_ANI_BIG_RUN_LEFT_MAXSPEED		23
#define MARIO_ANI_BIG_FLY_RIGHT				24
#define MARIO_ANI_BIG_FLY_LEFT				25
#define MARIO_ANI_SMALL_FLY_RIGHT			26
#define MARIO_ANI_SMALL_FLY_LEFT			27

#define MARIO_ANI_FIRE_IDLE_RIGHT			28
#define MARIO_ANI_FIRE_IDLE_LEFT			29
#define MARIO_ANI_FIRE_WALK_RIGHT			30
#define MARIO_ANI_FIRE_WALK_LEFT			31
#define MARIO_ANI_FIRE_RUN_RIGHT			32
#define MARIO_ANI_FIRE_RUN_LEFT				33
#define MARIO_ANI_FIRE_JUMP_RIGHT			34
#define MARIO_ANI_FIRE_JUMP_LEFT			35
#define MARIO_ANI_FIRE_SIT_RIGHT			36
#define MARIO_ANI_FIRE_SIT_LEFT				37
#define MARIO_ANI_FIRE_TURN_RIGHT			38
#define MARIO_ANI_FIRE_TURN_LEFT			39
#define MARIO_ANI_FIRE_RUN_RIGHT_MAXSPEED	40
#define MARIO_ANI_FIRE_RUN_LEFT_MAXSPEED	41
#define MARIO_ANI_FIRE_FLY_RIGHT			42
#define MARIO_ANI_FIRE_FLY_LEFT				43
#define MARIO_ANI_DIE						100

#define	MARIO_LEVEL_SMALL	51
#define	MARIO_LEVEL_BIG		52
#define MARIO_LEVEL_FIRE	53
#define MARIO_BIG_BBOX_WIDTH  15
#define MARIO_BIG_BBOX_HEIGHT 27
#define MARIO_SMALL_BBOX_WIDTH  13
#define MARIO_SMALL_BBOX_HEIGHT 15
#define MARIO_BIG_BBOX_SIT_WIDTH  15
#define MARIO_BIG_BBOX_SIT_HEIGHT 18
#define MARIO_UNTOUCHABLE_TIME 5000
